// Generated by CoffeeScript 1.6.3
(function() {
  var fs, http, io, server, socketio, staticResponse;

  fs = require('fs');

  http = require('http');

  socketio = require('socket.io');

  server = http.createServer(function(req, res) {
    res.writeHead({
      "Content-type": "text/plain"
    });
    if (req.url === '/') {
      return staticResponse("public/index.html", res);
    } else if (req.url === "/favicon.ico") {
      return staticResponse("public/favicon.jpeg", res);
    } else {
      throw "no such resource";
    }
  });

  staticResponse = function(fileName, res) {
    return fs.readFile(fileName, function(err, data) {
      if (err) {
        throw err;
      }
      res.write(data);
      return res.end();
    });
  };

  server.listen(3000);

  io = socketio.listen(server);

  io.sockets.on('connection', function(socket) {
    console.log('Socket connected!');
    socket.on('message', function(data) {
      console.log(data);
      return socket.emit('echo', data);
    });
    return setInterval(function() {
      return socket.emit('pushedMessage', "THIS IS A REMINDERP");
    }, 5000);
  });

}).call(this);
